# This is a basic workflow to help you get started with Actions

name: GitlabSync

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    
      - name: Set up git repository
        run: |
          git config --global user.email "bruno.jeanluke@icloud.com"
          git config --global user.name "Bruno Robert"
          git clone ${{ secrets.CURRENT_REMOTE_REPOSITORY_URL }}
          cd ./polybiblioglot
          git config pull.rebase false

      - name: Add gitlab remote and push changes
        run: |
          echo adding remote
          git remote add gitlab ${{ secrets.REMOTE_REPOSITORY_URL }}
          echo pulling from gitlab
          git pull gitlab master
          echo status:
          git status
          echo pushing to gitlab
          git push gitlab HEAD:master
